on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '14.x'

name: Node.js

jobs:
  build-and-deploy:
    # GLIBC_2.29 対応
    # https://docs.microsoft.com/en-us/answers/questions/236856/microsoft-web-app-service-error-39version-glibc-22.html
    runs-on: ubuntu-18.04
    steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: 'npm install, build, and test'
        run: |
          rm -rf node_modules
          npm install
          echo "PORT=8080" >> .env
          echo "AUTHORIZATION=${{secrets.AUTHORIZATION}}" >> .env

      # deploy web app using Azure credentials
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'vocaloid-karaoke-ranking-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
